name: Create Release Tag

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-publish:
    name: Create Release Tag
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
    - name: Get Current Version
      run: echo -n "current_version=$(grep "version" setup.cfg | cut -d '=' -f2 | tr -d ' \t\n\r')" >> $GITHUB_ENV
    - name: Create Release Tag
      env:
        commit_name: bot-edgepi
        commit_email: bot@edgepi.com
        username: bot-edgepi
      run: |
        git config user.name ${{ env.commit_name }}
        git config user.email ${{ env.commit_email }}
        git tag -a release/v${{ env.current_version }} -m "tag release version ${{ env.current_version }}"
        git push origin release/v${{ env.current_version }}