# This workflow will lint all files in repo using pylint

name: pylint

on:
  push:
    branches:
      - dev
      - staging
      - main
    paths-ignore:
      - version
  pull_request:
    branches:
      - dev
      - staging
      - main
    paths-ignore:
      - version

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
          git config --global url."https://${{ secrets.BOT_OSENSA_TOKEN }}@github".insteadOf ssh://git@github
          python -m pip install --upgrade pip
          python -m venv venv_test
          source venv_test/bin/activate
          python -m pip install -r requirements_test.txt
    - name: Analysing the code with pylint
      run: |
        source venv_test/bin/activate
        pylint $(git ls-files '*.py')
