# name: Python Integration Test

# on:
#   push:
#     branches:
#       - dev
#       - staging
#       - main
#     paths-ignore:
#       - version
#   pull_request:
#     branches:
#       - dev
#       - staging
#       - main
#     paths-ignore:
#       - version

# jobs:
#   test:
#     name: Integration Tests
#     runs-on: ubuntu-latest
#     strategy:
#       fail-fast: false
#       matrix:
#         python-version: ["3.9"]

#     steps:
#       - name: Checkout
#         if: ${{ github.event_name  == 'pull_request'}}
#         uses: actions/checkout@v3
#         with:
#           ref: ${{ github.head_ref }}
#       - name: Checkout
#         if: ${{ github.event_name  == 'push'}}
#         uses: actions/checkout@v3
#         with:
#           ref: ${{ github.ref_name }}
#       - name: Install Dependencies
#         run: |
#           python -m pip install --upgrade pip
#           python -m venv venv_test
#           source venv_test/bin/activate
#           python -m pip install -r requirements_test.txt
#       - name: Test with pytest
#         run: |
#           source venv_test/bin/activate
#           pytest ./tests/integration -vvs
